<?php
/**
 * Created by PhpStorm.
 * User: dinko
 * Date: 19.02.19.
 * Time: 11:37
 */

namespace App\Repository;

use App\Entity\Seller;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

class SellerRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Seller::class);
    }

    public function findOneBy(array $criteria, array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy); // TODO: Change the autogenerated stub
    }

    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

    public function updateSellerToVerify($user)
    {
        return $this->createQueryBuilder('s')
            ->update()
            ->set('s.verified', 1)
            ->where('s.user=:user_id')
            ->setParameter('user_id', $user)
            ->getQuery()
            ->getResult();
    }

    public function updateSellerToUnverify($user)
    {
        return $this->createQueryBuilder('s')
            ->update()
            ->set('s.verified', 0)
            ->where('s.user=:user_id')
            ->setParameter('user_id', $user)
            ->getQuery()
            ->getResult();
    }
}